name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake-build-type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/ginkgo
        key: dependencies-${{ runner.os }}-${{ hashFiles('**/*.txt') }}
        restore-keys: |
          dependencies-${{ runner.os }}-

    - name: Install Ginkgo
      run: |
        if [ ! -d ~/.cache/ginkgo ]; then
          git clone https://github.com/ginkgo-project/ginkgo.git
          cd ginkgo
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install
          cd ../..
        fi
