name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake-build-type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/ginkgo
          ~/.cache/opencv
          /usr/src/gtest
        key: dependencies-${{ runner.os }}-${{ hashFiles('**/*.txt') }}
        restore-keys: |
          dependencies-${{ runner.os }}-

    - name: Install Ginkgo
      run: |
        if [ ! -d ~/.cache/ginkgo ]; then
          git clone https://github.com/ginkgo-project/ginkgo.git
          cd ginkgo
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install
          cd ../..
        fi

    - name: Install Google Test
      run: |
        if [ ! -d /usr/src/gtest ]; then
          sudo apt-get update
          sudo apt-get install -y libgtest-dev
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo mv libgtest* /usr/lib/
          cd -
        fi

    - name: Install OpenCV
      run: |
        if [ ! -d ~/.cache/opencv ]; then
          sudo apt-get update
          sudo apt-get install -y libopencv-dev
        fi

    - name: Build and Test
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }} ..
        make
        ctest --output-on-failure
